runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: postgres://poadmin:poadmin@localhost:5432/mining
  APP_ID: myAppId
  MASTER_KEY: master_KEY
  SERVER_URL: http://localhost:1337
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
